name: Build and push image to ECR
on:
  release:
    types: [created]
jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: catalystsquad/action-build-push-image-ecr@v1
        with:
          aws-access-key-id: ${{ secrets.CICD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CICD_AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.COMMON_CICD_ROLE_ARN }}
          aws-region: us-west-2
          extra-account-access: 941986904600,378091611520 # nonprod, prod
          build-secrets: |
            "GIT_PAT=${{ secrets.AUTOMATION_PAT }}"
