name: Release
on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - 'cmd/**'
      - 'internal/**'
      - Dockerfile
      - 'go.mod'
      - 'go.sum'
jobs:
  release:
    runs-on: ubuntu-latest
    name: Release and update helm chart
    steps:
      - uses: catalystsquad/action-release-update-chart@v1
        with:
          token: ${{ secrets.AUTOMATION_PAT }}
